#!/usr/bin/env python
#
# This file is part of CL-Ops.
#
# CL-Ops is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CL-Ops is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CL-Ops. If not, see <http://www.gnu.org/licenses/>.

## @file
# A script to plot random data generated by clo_rng_test in a human
# readable fashion. Data is read from the out*.tsv files in current
# folder.

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import re
import glob
import os
import math

# Get sorted list of files in current folder
os.chdir('.')
files = sorted(glob.glob('out*.tsv'))

# Determine how many files there are (and thus, the number of subplots),
# and chose a nice number of rows and columns, a cell of which for each
# subplot.
n = len(files)
cols = int(math.sqrt(n))
rows = int(math.ceil(n / float(cols)))

# Current subplot
current = 1

# Create a figure
plt.figure(1)

# Cycle through files and plot the data for each
for f in files:
    # Load current file
    img = np.loadtxt(f, dtype=np.uint32)
    # Plot respective data into a subplot
    plt.subplot(rows,cols,current)
    imgplot = plt.imshow(img)
    # Set a title which corresponds to the plotted data
    t = re.split('_|\.', f)
    plt.title(t[1] + ', ' + t[2] + ' seeds (' + t[3] + ')')
    # Remove axis
    plt.axis('off')
    # Next file
    current+=1

# Show plot
plt.show()
