#!/usr/bin/env python
# rng_plot.py
 
"""
Plots random data generated by clo_rng_test in a human readable fashion.
Data is read from the out*.tsv files in current folder.
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import re
import glob
import os
import math

# Get sorted list of files in current folder
os.chdir('.')
files = sorted(glob.glob('out*.tsv'))

# Determine how many files there are (and thus, the number of subplots),
# and chose a nice number of rows and columns, a cell of which for each
# subplot.
n = len(files)
cols = int(math.sqrt(n))
rows = int(math.ceil(n / float(cols)))

# Current subplot
current = 1

# Create a figure
plt.figure(1)

# Cycle through files and plot the data for each
for f in files:
    # Load current file
    img = np.loadtxt(f, dtype=np.uint32)
    # Plot respective data into a subplot
    plt.subplot(rows,cols,current)
    imgplot = plt.imshow(img)
    # Set a title which corresponds to the plotted data
    t = re.split('_|\.', f)
    plt.title(t[1] + ', ' + t[2] + ' seeds (' + t[3] + ')')
    # Remove axis
    plt.axis('off')
    # Next file
    current+=1

# Show plot
plt.show()
